apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  APP_VERSION: {{ .Values.app.version | quote }}
  RELEASE_MODE: {{ .Values.app.releaseMode | quote }}
